name = "Holloway's HestiaHUGO"
license = "Apache-2.0"
licenselink = "https://github.com/ChewKeanHo/LIBS_HestiaHUGO/blob/main/LICENSE.txt"
description = """
One Peaceful Frontend+Backend Library Suite; by Developers, for Developers.
"""
homepage = "https://github.com/ChewKeanHo/LIBS_HestiaHUGO"
tags = [
        "hestia",
        "theme",
        "web",
        "ui",
        "design",
        "components",
        "wasm",
        "pwa",
        "favicon rendered",
]
features = [
        "W3C Compliant HTML",
        "Go Compatible Template Modules",
        "WASM Compatible",
        "Configurable Theme",
        "Built-in Functions for Long Terms Maintenance and Sustainability",
        "Continuously Improved",
        "UI Component Compiling Driven Approach",
        "Built-in PWA Supports",
        "Built-in Favicons and Icons Rendering Supports",
        "Open Graph Rendering",
        "JSON Data-Driven Capable",
        "PWA Offline Mode Supports",
]
min_version = "0.111.3"

authors = [
	{name = "Holloway Chew Kean Ho", homepage = "https://www.hollowaykeanho.com"},
]
